//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_search
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Id
    {
        public int App_Id1 { get; set; }
        public int User_id { get; set; }
        public Nullable<int> Job_Id { get; set; }
        public string CV { get; set; }
        public string App_date { get; set; }
        public string App_Status { get; set; }
    }
}
